### ISSUE TITLE
TODO -Development

### ISSUE THREAD

**Issue by Pale91** [Pale91/the-list#15]
- [ ] Prevent XSS attack
- [ ] Protect server actions with authorization
- [ ] Create admin form
- [ ] Validate files as images in the server (Prevent JS scripts)
- [ ] Submit images Firestore
